-- Generated by Oracle SQL Developer Data Modeler 4.2.0.921
--   at:        2017-11-07 22:49:24 CST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE tbl_capacidad_habitacion (
    codigo_capacidad_habitacion   INTEGER NOT NULL,
    capacidad                     VARCHAR2(4000) NOT NULL
);

ALTER TABLE tbl_capacidad_habitacion ADD CONSTRAINT tbl_capacidad_habitacion_pk PRIMARY KEY ( codigo_capacidad_habitacion );

CREATE TABLE tbl_categoria (
    codigo_categoria   INTEGER NOT NULL,
    categoria          VARCHAR2(500 CHAR) NOT NULL
);

ALTER TABLE tbl_categoria ADD CONSTRAINT tbl_categoria_pk PRIMARY KEY ( codigo_categoria );

CREATE TABLE tbl_ciudad (
    codigo_ciudad   INTEGER NOT NULL,
    nombre_ciudad   VARCHAR2(500 CHAR) NOT NULL,
    codigo_pais     INTEGER NOT NULL
);

ALTER TABLE tbl_ciudad ADD CONSTRAINT tbl_ciudad_pk PRIMARY KEY ( codigo_ciudad );

CREATE TABLE tbl_comentario (
    codigo_comentario   INTEGER NOT NULL,
    codigo_hotel        INTEGER NOT NULL,
    codigo_usuario      INTEGER NOT NULL,
    comentario          VARCHAR2(2000 BYTE) NOT NULL,
    fecha               DATE NOT NULL
);

ALTER TABLE tbl_comentario ADD CONSTRAINT tbl_comentario_pk PRIMARY KEY ( codigo_comentario );

CREATE TABLE tbl_estadia (
    codigo_estadia   INTEGER NOT NULL,
    tiempo_estadia   INTEGER
);

ALTER TABLE tbl_estadia ADD CONSTRAINT tbl_estadia_pk PRIMARY KEY ( codigo_estadia );

CREATE TABLE tbl_estadia_x_hotel (
    codigo_estadia   INTEGER NOT NULL,
    codigo_hotel     INTEGER NOT NULL
);

CREATE TABLE tbl_estado_reservacion (
    codigo_estado_reservacion   INTEGER NOT NULL,
    estado_reservacion          VARCHAR2(200)
);

ALTER TABLE tbl_estado_reservacion ADD CONSTRAINT tbl_estado_reservacion_pk PRIMARY KEY ( codigo_estado_reservacion );

CREATE TABLE tbl_fotos_hoteles (
    codigo_foto_hotel   INTEGER NOT NULL,
    codigo_hotel        INTEGER NOT NULL,
    nombre_foto         VARCHAR2(500),
    foto                blob
);

ALTER TABLE tbl_fotos_hoteles ADD CONSTRAINT tbl_fotos_hoteles_pk PRIMARY KEY ( codigo_foto_hotel );

CREATE TABLE tbl_genero (
    codigo_genero   INTEGER NOT NULL,
    tipo_genero     VARCHAR2(500 CHAR) NOT NULL
);

ALTER TABLE tbl_genero ADD CONSTRAINT tbl_genero_pk PRIMARY KEY ( codigo_genero );

CREATE TABLE tbl_habitacion (
    codigo_habitacion             INTEGER NOT NULL,
    codigo_tipo_habitacion        INTEGER NOT NULL,
    codigo_capacidad_habitacion   INTEGER NOT NULL,
    numero_habitacion             INTEGER NOT NULL,
    cantidad_disponibles          INTEGER,
    cantidad_reservadas           INTEGER
);

ALTER TABLE tbl_habitacion ADD CONSTRAINT tbl_habitacion_pk PRIMARY KEY ( codigo_habitacion );

CREATE TABLE tbl_habitacion_x_hotel (
    codigo_hotel        INTEGER NOT NULL,
    codigo_habitacion   INTEGER NOT NULL,
    precio_habitacion   NUMBER NOT NULL
);

ALTER TABLE tbl_habitacion_x_hotel ADD CONSTRAINT tbl_tipo_x_hotel_pk PRIMARY KEY ( codigo_hotel,codigo_habitacion );

CREATE TABLE tbl_historial_busqueda (
    codigo_hotel     INTEGER,
    codigo_ciudad    INTEGER,
    codigo_usuario   INTEGER NOT NULL,
    fecha            TIMESTAMP WITH LOCAL TIME ZONE,
    id_busqueda      INTEGER NOT NULL
);

ALTER TABLE tbl_historial_busqueda ADD CONSTRAINT prueba_pk PRIMARY KEY ( id_busqueda );

ALTER TABLE tbl_historial_busqueda ADD CONSTRAINT prueba__un UNIQUE ( codigo_ciudad,codigo_hotel );

CREATE TABLE tbl_hotelero (
    codigo_hotelero   INTEGER NOT NULL,
    codigo_hotel      INTEGER NOT NULL,
    nombre            VARCHAR2(200),
    codigo_genero     INTEGER NOT NULL,
    apellido          VARCHAR2(200),
    "CORREO "         VARCHAR2(200),
    contrasena        VARCHAR2(200)
);

ALTER TABLE tbl_hotelero ADD CONSTRAINT tbl_hotelero_pk PRIMARY KEY ( codigo_hotelero );

CREATE TABLE tbl_hoteles (
    codigo_hotel    INTEGER NOT NULL,
    codigo_ciudad   INTEGER NOT NULL,
    nombre_hotel    VARCHAR2(2000 BYTE) NOT NULL,
    direccion       VARCHAR2(2000 BYTE) NOT NULL,
    estrellas       INTEGER
);

ALTER TABLE tbl_hoteles ADD CONSTRAINT tbl_hoteles_pk PRIMARY KEY ( codigo_hotel );

CREATE TABLE tbl_hoteles_favoritos (
    codigo_hotel     INTEGER NOT NULL,
    codigo_usuario   INTEGER NOT NULL,
    comentario       VARCHAR2(2000 BYTE)
);

ALTER TABLE tbl_hoteles_favoritos ADD CONSTRAINT tbl_hoteles_favoritos_pk PRIMARY KEY ( codigo_hotel );

CREATE TABLE tbl_opiniones (
    codigo_usuario     INTEGER NOT NULL,
    codigo_categoria   INTEGER NOT NULL,
    codigo_hotel       INTEGER NOT NULL,
    puntaje            INTEGER
);

ALTER TABLE tbl_opiniones ADD CONSTRAINT tbl_opiniones_pk PRIMARY KEY ( codigo_categoria,codigo_hotel );

CREATE TABLE tbl_pais (
    codigo_pais   INTEGER NOT NULL,
    nombre_pais   VARCHAR2(500 CHAR) NOT NULL
);

ALTER TABLE tbl_pais ADD CONSTRAINT tbl_pais_pk PRIMARY KEY ( codigo_pais );

CREATE TABLE tbl_reservaciones (
    codigo_reservacion          INTEGER NOT NULL,
    codigo_hotel                INTEGER NOT NULL,
    codigo_habitacion           INTEGER NOT NULL,
    codigo_usuario              INTEGER NOT NULL,
    codigo_estado_reservacion   INTEGER NOT NULL,
    fecha_entrada               DATE,
    fecha_salida                DATE,
    numero_adultos              INTEGER,
    numero_niños                INTEGER
);

ALTER TABLE tbl_reservaciones ADD CONSTRAINT tbl_reservaciones_pk PRIMARY KEY ( codigo_reservacion );

CREATE TABLE tbl_servicios (
    codigo_servicio   INTEGER NOT NULL,
    servicio          VARCHAR2(1000) NOT NULL
);

ALTER TABLE tbl_servicios ADD CONSTRAINT tbl_servicios_pk PRIMARY KEY ( codigo_servicio );

CREATE TABLE "TBL_SERVICIOS_POR _HOTEL" (
    codigo_hotel      INTEGER NOT NULL,
    codigo_servicio   INTEGER NOT NULL
);

ALTER TABLE "TBL_SERVICIOS_POR _HOTEL" ADD CONSTRAINT "TBL_SERVICIOS_POR _HOTEL_PK" PRIMARY KEY ( codigo_hotel,codigo_servicio );

CREATE TABLE tbl_temporada (
    codigo_temporada   INTEGER NOT NULL,
    temporada          VARCHAR2(500 CHAR) NOT NULL
);

ALTER TABLE tbl_temporada ADD CONSTRAINT tbl_temporada_pk PRIMARY KEY ( codigo_temporada );

CREATE TABLE tbl_temporada_x_hotel (
    codigo_temporada    INTEGER NOT NULL,
    codigo_hotel        INTEGER NOT NULL,
    porcentaje_cambio   float
);

ALTER TABLE tbl_temporada_x_hotel ADD CONSTRAINT tbl_temporada_x_hotel_pk PRIMARY KEY ( codigo_temporada,codigo_hotel );

CREATE TABLE tbl_tipo_habitacion (
    codigo_tipo_habitacion   INTEGER NOT NULL,
    tipo_habitacion          VARCHAR2(500 BYTE) NOT NULL,
    precio_habitacion        NUMBER NOT NULL
);

ALTER TABLE tbl_tipo_habitacion ADD CONSTRAINT tbl_tipo_habitacion_pk PRIMARY KEY ( codigo_tipo_habitacion );

CREATE TABLE tbl_usuario (
    codigo_usuario        INTEGER NOT NULL,
    codigo_genero         INTEGER NOT NULL,
    codigo_ciudad         INTEGER NOT NULL,
    codigo_postal         VARCHAR2(500 CHAR) NOT NULL,
    codigo_tipo_usuario   INTEGER NOT NULL,
    nombre                VARCHAR2(500 CHAR) NOT NULL,
    apellido              VARCHAR2(500 CHAR) NOT NULL,
    correo_electronico    VARCHAR2(500 CHAR) NOT NULL,
    contrasenia           VARCHAR2(500 CHAR) NOT NULL,
    direccion             VARCHAR2(500 CHAR),
    foto                  blob
);

ALTER TABLE tbl_usuario ADD CONSTRAINT tbl_persona_pk PRIMARY KEY ( codigo_usuario );

ALTER TABLE tbl_historial_busqueda ADD CONSTRAINT prueba_tbl_ciudad_fk FOREIGN KEY ( codigo_ciudad )
    REFERENCES tbl_ciudad ( codigo_ciudad );

ALTER TABLE tbl_historial_busqueda ADD CONSTRAINT prueba_tbl_hoteles_fk FOREIGN KEY ( codigo_hotel )
    REFERENCES tbl_hoteles ( codigo_hotel );

ALTER TABLE tbl_hoteles ADD CONSTRAINT tbl_ciudad FOREIGN KEY ( codigo_ciudad )
    REFERENCES tbl_ciudad ( codigo_ciudad );

ALTER TABLE tbl_ciudad ADD CONSTRAINT tbl_ciudad_tbl_pais_fk FOREIGN KEY ( codigo_pais )
    REFERENCES tbl_pais ( codigo_pais );

ALTER TABLE tbl_comentario ADD CONSTRAINT tbl_coment_tbl_person_fk FOREIGN KEY ( codigo_usuario )
    REFERENCES tbl_usuario ( codigo_usuario );

ALTER TABLE tbl_comentario ADD CONSTRAINT tbl_comentario_tbl_hoteles_fk FOREIGN KEY ( codigo_hotel )
    REFERENCES tbl_hoteles ( codigo_hotel );

ALTER TABLE tbl_estadia_x_hotel ADD CONSTRAINT tbl_esta_x_hotel_tbl_esta_fk FOREIGN KEY ( codigo_estadia )
    REFERENCES tbl_estadia ( codigo_estadia );

ALTER TABLE tbl_estadia_x_hotel ADD CONSTRAINT tbl_esta_x_hotel_tbl_hot_fk FOREIGN KEY ( codigo_hotel )
    REFERENCES tbl_hoteles ( codigo_hotel );

ALTER TABLE tbl_fotos_hoteles ADD CONSTRAINT tbl_fotos_tbl_hot_fk FOREIGN KEY ( codigo_hotel )
    REFERENCES tbl_hoteles ( codigo_hotel );

ALTER TABLE tbl_habitacion ADD CONSTRAINT tbl_hab_tbl_cap_hab_fk FOREIGN KEY ( codigo_capacidad_habitacion )
    REFERENCES tbl_capacidad_habitacion ( codigo_capacidad_habitacion );

ALTER TABLE tbl_habitacion ADD CONSTRAINT tbl_hab_tbl_tipo_hab_fk FOREIGN KEY ( codigo_tipo_habitacion )
    REFERENCES tbl_tipo_habitacion ( codigo_tipo_habitacion );

ALTER TABLE tbl_historial_busqueda ADD CONSTRAINT tbl_his_bus_tbl_per_fk FOREIGN KEY ( codigo_usuario )
    REFERENCES tbl_usuario ( codigo_usuario );

ALTER TABLE tbl_hoteles_favoritos ADD CONSTRAINT tbl_hot_fav_tbl_hot_fk FOREIGN KEY ( codigo_hotel )
    REFERENCES tbl_hoteles ( codigo_hotel );

ALTER TABLE tbl_hoteles_favoritos ADD CONSTRAINT tbl_hot_fav_tbl_usu_fk FOREIGN KEY ( codigo_usuario )
    REFERENCES tbl_usuario ( codigo_usuario );

ALTER TABLE tbl_hotelero ADD CONSTRAINT tbl_hotelero_tbl_genero_fk FOREIGN KEY ( codigo_genero )
    REFERENCES tbl_genero ( codigo_genero );

ALTER TABLE tbl_hotelero ADD CONSTRAINT tbl_hotelero_tbl_hoteles_fk FOREIGN KEY ( codigo_hotel )
    REFERENCES tbl_hoteles ( codigo_hotel );

ALTER TABLE tbl_opiniones ADD CONSTRAINT tbl_opiniones_tbl_categoria_fk FOREIGN KEY ( codigo_categoria )
    REFERENCES tbl_categoria ( codigo_categoria );

ALTER TABLE tbl_opiniones ADD CONSTRAINT tbl_opiniones_tbl_hoteles_fk FOREIGN KEY ( codigo_hotel )
    REFERENCES tbl_hoteles ( codigo_hotel );

ALTER TABLE tbl_opiniones ADD CONSTRAINT tbl_opiniones_tbl_persona_fk FOREIGN KEY ( codigo_usuario )
    REFERENCES tbl_usuario ( codigo_usuario );

ALTER TABLE tbl_usuario ADD CONSTRAINT tbl_persona_tbl_ciudad_fk FOREIGN KEY ( codigo_ciudad )
    REFERENCES tbl_ciudad ( codigo_ciudad );

ALTER TABLE tbl_usuario ADD CONSTRAINT tbl_persona_tbl_genero_fk FOREIGN KEY ( codigo_genero )
    REFERENCES tbl_genero ( codigo_genero );

ALTER TABLE tbl_reservaciones ADD CONSTRAINT tbl_res_tbl_est_res_fk FOREIGN KEY ( codigo_estado_reservacion )
    REFERENCES tbl_estado_reservacion ( codigo_estado_reservacion );

ALTER TABLE tbl_reservaciones ADD CONSTRAINT tbl_res_tbl_ho_fk FOREIGN KEY ( codigo_hotel )
    REFERENCES tbl_hoteles ( codigo_hotel );

ALTER TABLE tbl_reservaciones ADD CONSTRAINT tbl_res_tbl_per_fk FOREIGN KEY ( codigo_usuario )
    REFERENCES tbl_usuario ( codigo_usuario );

ALTER TABLE tbl_reservaciones ADD CONSTRAINT tbl_rese_tbl_hab_fk FOREIGN KEY ( codigo_habitacion )
    REFERENCES tbl_habitacion ( codigo_habitacion );

ALTER TABLE "TBL_SERVICIOS_POR _HOTEL" ADD CONSTRAINT tbl_ser_hol_tbl_ser_fk FOREIGN KEY ( codigo_servicio )
    REFERENCES tbl_servicios ( codigo_servicio );

ALTER TABLE "TBL_SERVICIOS_POR _HOTEL" ADD CONSTRAINT tbl_ser_tbl_hot_fk FOREIGN KEY ( codigo_hotel )
    REFERENCES tbl_hoteles ( codigo_hotel );

ALTER TABLE tbl_temporada_x_hotel ADD CONSTRAINT tbl_temp_x_hotel_tbl_hot FOREIGN KEY ( codigo_hotel )
    REFERENCES tbl_hoteles ( codigo_hotel );

ALTER TABLE tbl_habitacion_x_hotel ADD CONSTRAINT tbl_tipo_x_hotel_tbl_hab FOREIGN KEY ( codigo_habitacion )
    REFERENCES tbl_habitacion ( codigo_habitacion );

ALTER TABLE tbl_habitacion_x_hotel ADD CONSTRAINT tbl_tipo_x_hotel_tbl_hot_fk FOREIGN KEY ( codigo_hotel )
    REFERENCES tbl_hoteles ( codigo_hotel );

ALTER TABLE tbl_temporada_x_hotel ADD CONSTRAINT temp_x_hotel_tbl_tem_fk FOREIGN KEY ( codigo_temporada )
    REFERENCES tbl_temporada ( codigo_temporada );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            24
-- CREATE INDEX                             0
-- ALTER TABLE                             55
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
